services:
  mcpgateway:
    provider:
      type: mcpgateway
      options:
        tools: get_me, mcp/duckduckgo:*, SQLite:list-tables
        log_calls: yes
        scan_secrets: yes
        verify_signatures: yes

  agents:
    image: demo/agents
    ports:
      - "7777:7777"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    volumes:
      - ./agents.yaml:/agents.yaml
    depends_on:
      - mcpgateway
      - gemma

  agents-ui:
    image: demo/ui
    ports:
      - "3000:3000"
    environment:
      - AGENTS_URL=http://localhost:7777
    depends_on:
      - agents

  gemma:
    provider:
      type: model
      options:
        model: ai/gemma3
