services:
  ui:
    image: demo/ui
    build:
      context: agent-ui
    ports:
      - "3000:3000"

  agent:
    image: demo/agents
    build:
      context: agent
    environment:
      - OPENAI_API_KEY
    depends_on:
      - mcpgateway
      - gemma

  mcpgateway:
    provider:
      type: mcpgateway
      options:
        tools: get_me,create-table,fetch_content,search
        log_calls: yes
        scan_secrets: yes

  gemma:
    provider:
      type: model
      options:
        model: ai/gemma3
