services:
  agents:
    provider:
      type: agentic
      options:
        config: agents.yaml
        openai_api_key: $OPENAI_API_KEY
        ui_port: 3000
    depends_on:
      - mcpgateway
      - gemma

  mcpgateway:
    provider:
      type: mcpgateway
      options:
        tools: get_me, mcp/duckduckgo:*, SQLite:list-tables
        log_calls: yes
        scan_secrets: yes
        verify_signatures: yes

  gemma:
    provider:
      type: model
      options:
        model: ai/gemma3
