services:
  ui:
    build:
      context: agent-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  agent:
    build:
      context: agent
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - OPENAI_API_KEY
      - MCPGATEWAY_ENDPOINT=agents_gateway:8811
    depends_on:
      - agents_gateway
      - gemma

  # This is an Agents Gateway that connects to a downstream MCP Gateway
  # And adds services on top, such as filtering, logging, etc.
  agents_gateway:
    image: docker/agents_gateway
    command:
      - --tools
      - get_me,create-table,fetch_content,search
      - --logCalls
      - --scanSecrets
    depends_on:
      - mcpgateway

  # This gives access to the MCP Gateway, either local to Docker Desktop
  # (or running in the cloud).
  mcpgateway:
    provider:
      type: mcpgateway

  # This is a local model.
  gemma:
    provider:
      type: model
      options:
        model: ai/gemma3
