services:
  mcpgateway:
    provider:
      type: mcpgateway
      options:
        tools: get_me, list_issues, mcp/duckduckgo:*, SQLite:list-tables, notion:*
        log_calls: yes
        scan_secrets: yes
        verify_signatures: yes

  llm:
    provider:
      type: model
      options:
        model: ai/gemma3

  agents:
    image: demo/agents
    ports:
      - "7777:7777"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./agents.yaml:/agents.yaml
#      - ./agents_with_tools.yaml:/agents.yaml
    depends_on:
      - mcpgateway
      - llm

  agents-ui:
    image: demo/ui
    ports:
      - "3000:3000"
    environment:
      - AGENTS_URL=http://localhost:7777
    depends_on:
      - agents
