services:
  ui:
    image: demo/ui
    build:
      context: agent-ui
    ports:
      - "3000:3000"

  agent:
    image: demo/agents
    build:
      context: agent
    ports:
      - "7777:7777"
    environment:
      - OPENAI_API_KEY
    depends_on:
      - mcpgateway
      - gemma

  # Connects to the MCP Gateway and adds services on top (secrets scan, logging, etc.)
  mcpgateway:
    provider:
      type: mcpgateway
      options:
        tools: get_me,create-table,fetch_content,search
        logCalls: yes
        scanSecrets: yes

  # Local model
  gemma:
    provider:
      type: model
      options:
        model: ai/gemma3
