services:
  agents:
    provider:
      type: agentic
      options:
        config: agents.yaml
        openai_api_key: $OPENAI_API_KEY
        # Disabled by default, comment to enable the API
        # api_port: "7777"
        ui_port: 3000
    depends_on:
      - mcpgateway
      - gemma
  ui:
    image: demo/ui
    build:
      context: agent-ui
    ports:
      - "3000:3000"

  mcpgateway:
    provider:
      type: mcpgateway
      options:
        servers: mcp/duckduckgo, mcp/github-mcp-server, mcp/sqlite
        config: mcp/github-mcp-server.GITHUB_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN
        tools: get_me, create-table, fetch_content, search
        log_calls: yes
        scan_secrets: yes

  gemma:
    provider:
      type: model
      options:
        model: ai/gemma3
