services:
  ui:
    image: demo/ui
    build:
      context: agent-ui
    ports:
      - "3000:3000"

  agent:
    image: demo/agents
    build:
      context: agent
    ports:
      - "7777:7777"
    environment:
      - OPENAI_API_KEY
      - MCPGATEWAY_ENDPOINT=agents_gateway:8811
    depends_on:
      - agents_gateway
      - gemma

  # Agents Gateway - connects to a MCP Gateway and adds services on top (secrets scan, logging, etc.)
  agents_gateway:
    image: demo/agents_gateway
    build:
      context: gateway
      target: agents_gateway
    command:
      - --tools
      - get_me,create-table,fetch_content,search
      - --logCalls
      - --scanSecrets
    depends_on:
      - mcpgateway

  # Enable the MCP Gateway (local to Docker Desktop for now)
  mcpgateway:
    provider:
      type: mcpgateway

  # Local model
  gemma:
    provider:
      type: model
      options:
        model: ai/gemma3
