version: "3"

tasks:
  default:
    cmds:
      - task: up

  up:
    desc: Start the demo Compose Stack
    cmd: docker compose up --build

  down:
    desc: Stop the demo Compose Stack
    cmd: docker compose down --remove-orphans
