version: "3"

tasks:
  default:
    cmds:
      - task: up

  up:
    desc: Start the demo Compose Stack
    cmd: docker compose up --build

  down:
    desc: Stop the demo Compose Stack
    cmd: docker compose down --remove-orphans

  build-compose:
    desc: Build docker-compose from the source
    cmds:
      - docker buildx build --target=binary-darwin --platform=darwin/arm64 --output type=local,dest=./out https://github.com/docker/compose.git
      - /bin/ln -sf "{{.TASKFILE_DIR}}/out/docker-compose" "{{.HOME}}/.docker/cli-plugins/docker-compose"
