version: "3"

dotenv: ['.env']

tasks:
  default:
    cmds:
      - task: up
      
  up:
    preconditions:
      - sh: '[ -n "$OPENAI_API_KEY" ]'
        msg: "OPENAI_API_KEY must be set and non-empty"
    desc: Start the demo Compose Stack
    cmd: docker compose up --build

  down:
    desc: Stop the demo Compose Stack
    cmd: docker compose down --remove-orphans

  push-gateway-image:
    desc: Build and push the gateway docker image
    cmd: docker buildx bake --file docker-bake.hcl --sbom="generator=docker/scout-sbom-indexer:1" --provenance=mode=max --set='*.platform=linux/arm64,linux/amd64' --push gateway

  build:
    desc: Build all binaries and images
    cmds:
      - cmd: docker buildx bake --file docker-bake.hcl darwin
        platforms: [darwin]
      - cmd: docker buildx bake --file docker-bake.hcl windows
        platforms: [windows]

  install-docker-mcpgateway:
    desc: Install the docker-mcpgateway CLI plugin
    cmds:
      - cmd: ln -sf "{{.TASKFILE_DIR}}/bin/docker-mcpgateway" "{{.HOME}}/.docker/cli-plugins/"
        platforms: [darwin]
      - cmd: ln -sf "{{.TASKFILE_DIR}}/bin/docker-mcpgateway.exe" "{{.USERPROFILE}}/.docker/cli-plugins/"
        platforms: [windows]

  install-docker-compose:
    desc: Install the docker-compose CLI plugin
    cmds:
      - cmd: ln -sf "{{.TASKFILE_DIR}}/bin/docker-compose" "{{.HOME}}/.docker/cli-plugins/"
        platforms: [darwin]
      - cmd: mkdir -p "{{.USERPROFILE}}/.docker/cli-plugins"
        platforms: [windows]
      - cmd: ln -sf "{{.TASKFILE_DIR}}/bin/docker-compose.exe" "{{.USERPROFILE}}/.docker/cli-plugins/"
        platforms: [windows]

  install:
    desc: Install all binaries
    deps:
      - build
      - install-docker-compose
      - install-docker-mcpgateway
