services:
  client:
    image: demo/client
    build:
      context: ..
      target: client_gateway
    command:
      - call
      - get_me
      # - ghp_cxLeRrvbJfmYdUtr70xnNE3Q7Gvli43s19PD
    depends_on:
      - mcpgateway

  mcpgateway:
    provider:
      type: mcpgateway
      options:
        tools: get_me, mcp/duckduckgo:*, SQLite:list-tables, notion:*
        log_calls: yes
        scan_secrets: yes
        verify_signatures: yes
