services:
  client:
    image: demo/client
    build:
      context: ..
      target: client_gateway
    command:
      - call
      - get_me
      # - ghp_cxLeRrvbJfmYdUtr70xnNE3Q7Gvli43s19PD
    depends_on:
      - mcpgateway

  mcpgateway:
    provider:
      type: mcpgateway
      options:
        config: mcp/github-mcp-server.GITHUB_PERSONAL_ACCESS_TOKEN=$GITHUB_TOKEN
        tools: get_me,create-table,fetch_content,search
        log_calls: yes
        scan_secrets: yes
