services:
  # This is an agent interacting with tools, through the Agents Gateway
  agent:
    image: demo/agent
    build:
      target: agent
    command:
      - call
      - get_me
      # - ghp_cxLeRrvbJfmYdUtr70xnNE3Q7Gvli43s19PD
    depends_on:
      - mcpgateway

  # Connects to the MCP Gateway and adds services on top (secrets scan, logging, etc.)
  mcpgateway:
    provider:
      type: mcpgateway
      options:
        tools: get_me,create-table,fetch_content,search
        log_calls: yes
        scan_secrets: yes
