version: "3"

tasks:
  default:
    desc: Build and run the Docker image
    cmds:
      - task: build
      - task: down
      - task: up

  up:
    desc: Start the demo Compose Stack
    cmd: docker compose up --build

  down:
    desc: Stop the demo Compose Stack
    cmd: docker compose down --remove-orphans

  build_and_install:
    cmds:
      - task -d .. build-gateway-image
      - task -d .. install-docker-mcpgateway
