version: "3"

tasks:
  default:
    desc: Build and run the Docker image
    cmds:
      - task: build_and_install
      - task: down
      - task: up

  build_and_install:
    desc: Build the gateway and compose provider
    aliases: ["build"]
    cmds:
      - task -d .. install

  up:
    desc: Start the demo Compose Stack
    cmd: docker --debug compose --progress=plain up --build

  down:
    desc: Stop the demo Compose Stack
    cmd: docker compose down --remove-orphans

