services:
  app:
    build:
      target: app
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - MCP_GATEWAY_URL=http://mcp-gateway:8811
      - QUESTION="Does Spring AI supports the Model Context Protocol? Please provide some references."
    depends_on:
      - mcp-gateway
      - model_runner
  mcp-gateway:
    image: docker/agents_gateway:v2
    ports:
      - 8811:8811
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - --transport=sse
      - --servers=duckduckgo
      - --tools=search
      - --tools=fetch_content

  model_runner:
    provider:
      type: model
      options:
        model: ai/gemma3-qat
