services:
  agents:
    build:
        context: .
    environment:
      - MCP_SERVER_URL=http://mcp-gateway:8811/sse
    restart: no
    depends_on:
      - mcp-gateway
    models:
      agent:
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL

  mcp-gateway:
    image: docker/agents_gateway:v2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - --transport=sse
      - --servers=duckduckgo
      - --tools=search,fetch_content

models:
  agent:
    model: ai/qwen3
    context_size: 8192
    runtime_flags:
      - --no-prefill-assistant
