services:
  agents:
    build:
        context: .
    environment:
      - MCP_SERVER_URL=http://mcp_gateway:8811/sse
    restart: no
    depends_on:
      - model_runner
      - mcp_gateway

  mcp_gateway:
    image: docker/agents_gateway:v2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - --transport=sse
      - --servers=duckduckgo
      - --tools=search,fetch_content

  model_runner:
    provider:
      type: model
      options:
        model: ai/qwen3
        runtime-flags: "--no-prefill-assistant"
        context-size: 8192
