services:
  mcp-gateway:
    image: docker/mcp-gateway:latest
    ports:
      - "8811:8811"
    command:
      - --block-secrets=true
      - --log-calls=true
      - --verify-signatures=true
      - --secrets=/run/secrets/mcp_secret
      - --verbose
      - --servers=github-official
      - --servers=notion
      - --servers=fetch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/host-services/backend.sock:/run/host-services/backend.sock
    secrets:
      - mcp_secret
  
  llm:
    provider:
      type: model
      options:
        model: ai/qwen3:14B-Q6_K
    environment:
      - LLAMA_ARGS=--ctx-size 8000 --jinja -ngl 100

  agents:
    image: demo/agents
    build:
      context: agent
    ports:
      - "7777:7777"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./agents.yaml:/agents.yaml
    depends_on:
      - llm
      - mcp-gateway

  agents-ui:
    image: demo/ui
    build:
      context: agent-ui
    ports:
      - "3000:3000"
    environment:
      - AGENTS_URL=http://localhost:7777
    depends_on:
      - agents

secrets:
  mcp_secret:
    file: ./.mcp.env
