services:

  adk-ui:
    build:
      context: .
      dockerfile: Dockerfile.adk-ui
    ports:
      - 3000:3000
    depends_on:
      - adk
    profiles: [dev]

  adk:
    build:
      context: .
    ports:
      # expose port for web interface
      - 8080:8080
    environment:
      # point adk at the MCP gateway
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
      # - OPENAI_MODEL_NAME=gpt4
    depends_on:
      - mcp-gateway
    # secrets:
    #   - openai-api-key
    models:
      gemma3 :
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL
    profiles: [dev]

  mcp-gateway:
    # mcp-gateway secures your MCP servers
    image: docker/mcp-gateway:latest
    ports:
      - 8811:8811
    use_api_socket: true
    volumes:
      - ~/.docker/mcp/catalogs:/app/catalogs
      - ~/.docker/mcp/config.yaml:/app/config.yaml
    command:
      - --transport=sse
      - --servers=fetch,brave,resend,curl,mongodb
      - --catalog=/app/catalogs/docker-mcp.yaml
      - --config=/mcp_config
      - --verbose
    configs:
      - mcp_config
    #secrets:
      #- mcp_secret
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/var/log/mongodb/mongod.log", "--logappend", "--setParameter", "logComponentVerbosity={network:{verbosity:0}}"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

models:
  gemma3:
    # pre-pull the model when starting Docker Model Runner
    model: ai/gemma3-qat:27B-Q4_K_M	
    context_size: 131000 # 35.5 GB VRAM
    runtime_flags:
      - --no-prefill-assistant

volumes:
  mongodb_data:

configs:
  mcp_config:
    content: |
      resend:
        reply_to: slimslenderslacks@gmail.com
        sender: slimslenderslacks@slimslenderslacks.com

secrets:
  openai-api-key:
    file: secret.openai-api-key
  mcp_secret:
    file: ./.mcp.env
