services:
  adk:
    build:
      context: .
    ports:
      # expose port for web interface
      - "8080:8080"
    environment:
      # point adk at the MCP gateway
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
    depends_on:
      # model_runner provider starts first then injects environment variables
      # MODEL_RUNNER_MODEL name
      # MODEL_RUNNER_URL OpenAI compatible API endpoint
      - model_runner
      - mcp-gateway

  model_runner:
    provider:
      type: model
      options:
        # pre-pull the model when starting Docker Model Runner
        model: ai/gemma3-qat:27B-Q4_K_M	
        # increase context size to handle search results
        # context-size: 20000

  mcp-gateway:
    # mcp-gateway secures your MCP servers
    image: docker/mcp-gateway:latest
    use_api_socket: true
    command:
      - --transport=sse
      # add any MCP servers you want to use
      - --servers=duckduckgo
