services:
  adk:
    build:
      context: .
    ports:
      # expose port for web interface
      - "8080:8080"
    environment:
      # point adk at the MCP gateway
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
    depends_on:
      # model_runner provider starts first then injects environment variables
      # MODEL_RUNNER_MODEL name
      # MODEL_RUNNER_URL OpenAI compatible API endpoint
      - model_runner

  model_runner:
    provider:
      type: model
      options:
        # pre-pull the model when starting Docker Model Runner
        model: ai/gemma3-qat:27B-Q4_K_M	
        # increase context size to handle search results
        context-size: 20000

  mcp-gateway:
    # agents_gateway secures your MCP servers
    image: docker/agents_gateway:v2
    ports:
      - "8811:8811"
    command:
      - --transport=sse
      # add any MCP servers you want to use
      - --servers=duckduckgo
    volumes:
      # mount docker socket to run MCP containers
      - /var/run/docker.sock:/var/run/docker.sock
