services:
  # mcpgateway:
  #   provider:
  #     type: mcpgateway
  #     options:
  #       tools: get_me, list_issues, mcp/duckduckgo:*, SQLite:list-tables, notion:*, fetch
  #       log_calls: yes
  #       scan_secrets: yes
  #       verify_signatures: yes

  mcp-gateway:
    image: docker/agents_gateway:v2
    ports:
      - "8811:8811"
    command:
      - --port=8811
      - --block-secrets=true
      - --log-calls=true
      - --verify-signatures=true
      - --secrets=/.env
      - --transport=stdio
      - --verbose
      - --tools=*
      - --servers=github-official
      - --catalog=http://desktop.docker.com/mcp/catalog/v2/catalog.yaml
      - --config=/.config.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .env:/.env
      - ~/.docker/mcp/config.yaml:/.config.yaml

  llm:
    provider:
      type: model
      options:
        model: olegselajev241/qwen3:14B-Q6_K
    environment:
      - LLAMA_ARGS=--ctx-size 8000 --jinja -ngl 100

  agents:
    image: demo/agents
    build:
      context: agent
    ports:
      - "7777:7777"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - MCPGATEWAY_ENDPOINT=mcp-gateway:8811
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./agents.yaml:/agents.yaml
    depends_on:
      - llm

  agents-ui:
    image: demo/ui
    build:
      context: agent-ui
    ports:
      - "3000:3000"
    environment:
      - AGENTS_URL=http://localhost:7777
    depends_on:
      - agents
