services:

  mcpgateway: !reset null

  mock-gateway:
    image: demo/mock-gateway
    build:
      context: mock-gateway
    ports:
      - "8080:8080"  # HTTP port for debugging
      - "8081:8081"  # TCP port for MCP protocol
    environment:
      - HTTP_PORT=8080
      - TCP_PORT=8081
      - MOCKS_DIR=/root/mocks
    volumes:
      - ./mock-gateway/mocks:/root/mocks

  agents:
    environment:
      - MCPGATEWAY_ENDPOINT=mock-gateway:8081
      - TOTO=pouet
    depends_on: !override
      - mock-gateway
      - llm
