version: "3"

vars:
  TEST_MODE: '{{.TEST_MODE | default "false"}}'

tasks:
  default:
    cmds:
      - task: up
      
  up:
    preconditions:
      - sh: '[ -n "$OPENAI_API_KEY" ]'
        msg: "OPENAI_API_KEY must be set and non-empty"
    desc: Start the Agno demo Compose Stack (use TEST_MODE=true for test environment)
    cmds:
      - |
        if [ "{{.TEST_MODE}}" = "true" ]; then
          echo "Starting test environment in detached mode..."
          docker compose -f demos/agno/compose.yaml -f demos/agno/compose.test.yaml up --build -d
        else
          echo "Starting in foreground mode..."
          docker compose -f demos/agno/compose.yaml up --build
        fi

  down:
    desc: Stop the Agno demo Compose Stack (use TEST_MODE=true for test environment)
    cmds:
      - |
        if [ "{{.TEST_MODE}}" = "true" ]; then
          echo "Stopping test environment..."
          docker compose -f demos/agno/compose.yaml -f demos/agno/compose.test.yaml down --remove-orphans
        else
          echo "Stopping normal environment..."
          docker compose -f demos/agno/compose.yaml down --remove-orphans
        fi

  test:
    desc: Test the Writer agent with a simple message (always detached)
    preconditions:
      - sh: '[ -n "$OPENAI_API_KEY" ]'
        msg: "OPENAI_API_KEY must be set and non-empty"
    deps:
      - task: up
        vars:
          TEST_MODE: "true"
    cmds:
      - defer: task agno:down
        vars:
          TEST_MODE: "true"
      - ./demos/agno/test-writer-agent.sh