version: "3"

vars:
  DETACHED: '{{.DETACHED | default "false"}}'

tasks:
  default:
    cmds:
      - task: up
      
  up:
    preconditions:
      - sh: '[ -n "$OPENAI_API_KEY" ]'
        msg: "OPENAI_API_KEY must be set and non-empty"
    desc: Start the Agno demo Compose Stack
    cmds:
      - |
        if [ "{{.DETACHED}}" = "true" ]; then
          echo "Starting in detached mode..."
          docker compose -f demos/agno/compose.yaml up --build -d
        else
          echo "Starting in foreground mode..."
          docker compose -f demos/agno/compose.yaml up --build
        fi

  down:
    desc: Stop the Agno demo Compose Stack
    cmd: docker compose -f demos/agno/compose.yaml down --remove-orphans

  test:
    desc: Test the Writer agent with a simple message
    deps:
      - task: up
        vars:
          DETACHED: "true"
    cmds:
      - defer: task agno:down
      - ./demos/agno/test-writer-agent.sh
