services:
  model_runner:
    provider:
      type: model
      options:
        # pre-pull the model on Docker Model Runner
        model: ai/gemma3-qat:27B-Q4_K_M	
        # context-size: 10000 # 18.6 GB VRAM
        # context-size: 80000 # 28.37 GB VRAM
        context-size: 131000 # 35.5 GB VRAM
