services:
  # Auditor Agent coordinates the entire fact-checking workflow
  auditor-agent-a2a:
    build:
      target: auditor-agent
    ports:
      - "8080:8080"
    environment:
      - CRITIC_AGENT_URL=http://critic-agent-a2a:8001
      - REVISER_AGENT_URL=http://reviser-agent-a2a:8001
    depends_on:
      # compose docker-model-runner provider injects environment variables
      - critic-agent-a2a
      - reviser-agent-a2a

  critic-agent-a2a:
    build:
      target: critic-agent
    environment:
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
    depends_on:
      # compose docker-model-runner provider injects environment variables
      - model_runner
      - mcp-gateway

  reviser-agent-a2a:
    build:
      target: reviser-agent
    environment:
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
    depends_on:
      # compose docker-model-runner provider injects environment variables
      - model_runner
      - mcp-gateway

  model_runner:
    provider:
      type: model
      options:
        # pre-pull the model on Docker Model Runner
        model: ai/gemma3:4B-Q4_0
        context-size: 10000 # 3.5 GB VRAM
        # context-size: 131000 # 7.6 GB VRAM

  mcp-gateway:
    # mcp-gateway secures your MCP servers
    image: docker/mcp-gateway:latest
    use_api_socket: true
    command:
      - --transport=sse
      - --servers=duckduckgo
