services:
  critic-agent-a2a:
    build:
      target: critic-agent
    ports:
      - "8001:8001"
    environment:
      - MCPGATEWAY_ENDPOINT=http://mcp-gateway:8811/sse
    depends_on:
      # compose docker-model-runner provider injects environment variables
      - docker-model-runner
      - mcp-gateway

  docker-model-runner:
    provider:
      type: model
      options:
        # pre-pull the model on Docker Model Runner
        #model: olegselajev241/qwen3:14B-Q6_K
        model: ai/gemma3-qat:27B-Q4_K_M	
        context-size: 20000

  mcp-gateway:
    image: docker/agents_gateway:v2
    ports:
      - "8811:8811"
    command:
      - --transport=sse
      - --servers=duckduckgo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
