version: "3"

vars:
  IMAGE_NAME: academic-research
  IMAGE_TAG: latest
  CONTAINER_NAME: academic-research-agent
  PORT: 8080

tasks:
  default:
    cmds:
      - task: up

  format:
    desc: Format the code using ruff
    cmd: uv run ruff format .

  check-format:
    desc: Check the code formatting
    cmd: uv run ruff check .

  check-types:
    desc: Check the code types using pyright
    cmd: uv run pyright .

  adk-web:
    desc: Run the ADK web UI with the critic agent
    cmd: uv run adk web src
    env:
      AGENT_CONFIG: agents/critic.yaml

  # Docker Compose commands
  up:
    desc: Start services with docker-compose
    cmd: docker compose up --build --wait

  down:
    desc: Stop and remove containers
    cmd: docker compose down --remove-orphans

  test:
    desc: Test the Critic agent
    cmds:
      - docker compose --verbose up -d --wait --build
      - >
        curl -X POST http://localhost:8001
        -H "Content-Type: application/json"
        -d '{
          "jsonrpc": "2.0",
          "id": "req-1",
          "method": "message/send",
          "params": {
            "id": "task-1",
            "message": {
              "messageId": "msg-1",
              "kind": "message",
              "role": "user",
              "parts": [
                { "kind": "text", "text": "Earth is flat" }
              ]
            },
            "skill": "fact_check_answer"
          }
        }' | jq
      - docker compose logs mcp-gateway
      - docker compose down --remove-orphans
