name: CI

on:
  push:
    paths:
      - '.github/workflows/ci.yaml'
      - 'a2a/**'
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/ci.yaml'
      - 'a2a/**'

jobs:
  check:
    name: Format & Type Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: a2a

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH  # Make uv available

      - name: Install task
        uses: arduino/setup-task@v1

      - name: Check format
        run: task check-format

      - name: Check types
        run: task check-types
